(function(){
'use strict';
var root=document.getElementById('root');
if(!root) return;
var presets=['#161918','#203025','#5b6470','#172a46','#6d4b35','#a33131','#ffffff','#d9d4c9','#b99552','#6f7f69'];
var sections=['body','leftSleeve','rightSleeve','collar','cuffs','sidePanels'];
var labels={body:'MAIN BODY',leftSleeve:'LEFT SLEEVE',rightSleeve:'RIGHT SLEEVE',collar:'COLLAR',cuffs:'CUFFS',sidePanels:'SIDE PANELS'};
var meshMap={body:['body'],leftSleeve:['left_sleeve','left sleeve'],rightSleeve:['right_sleeve','right sleeve'],collar:['collar'],cuffs:['left_cuff','right_cuff','left cuff','right cuff'],sidePanels:['side_panel_left','side_panel_right','side panel']};
var colors={body:'#203025',leftSleeve:'#203025',rightSleeve:'#203025',collar:'#161918',cuffs:'#161918',sidePanels:'#203025'};
var activeSection='body',activeSide='front',scene,camera,renderer,controls,garment,fabricCanvas,editorDesigns={front:null,back:null,leftSleeve:null,rightSleeve:null};

/* Render the entire studio immediately. A failed 3D CDN/model must never blank the page. */
root.innerHTML='<div class="studio-shell">'+
'<div class="studio-crumb">HOME / DESIGN STUDIO / <b>T-SHIRT</b></div><div class="studio-grid">'+
'<aside class="studio-panel"><h2>CHOOSE PRODUCT</h2><div class="product-list">'+
'<button class="product-item active"><img src="assets/designer-sketches/tshirt.png" alt="T-Shirt"><div><strong>T-Shirt</strong><span>Full 3D customization ready</span><br><i class="tiny-badge">3D READY</i></div></button>'+ 
[['polo','Polo'],['sports-jersey','Sports Jersey'],['hoodie','Premium Hoodie'],['poplin-shirt','Poplin Shirt']].map(function(x){return '<button class="product-item locked" data-coming="'+x[1]+'"><img src="assets/designer-sketches/'+x[0]+'.png" alt="'+x[1]+'"><div><strong>'+x[1]+'</strong><span>Model slot ready</span><br><i class="tiny-badge">MODEL NEXT</i></div></button>';}).join('')+
'</div><div class="section-divider"></div><div class="section-title">GARMENT SECTION</div><div class="section-buttons" id="sectionButtons">'+sections.map(function(s){return '<button data-section="'+s+'" class="'+(s===activeSection?'active':'')+'">'+labels[s]+'</button>';}).join('')+'</div>'+ 
'<div class="section-divider"></div><div class="section-title">COLOR</div><div class="color-row" id="swatches">'+presets.map(function(c){return '<button class="swatch" data-color="'+c+'" style="background:'+c+'" title="'+c+'"></button>';}).join('')+'</div>'+ 
'<div class="hex-row"><input id="hexInput" value="'+colors.body+'" maxlength="7"><input id="colorInput" type="color" value="'+colors.body+'"></div><div class="tech-note">Select each garment section independently. Changes are saved with your design configuration.</div></aside>'+ 
'<section class="viewer-card"><div class="viewer-top"><div><h1>Customize Your Own Design</h1><p>Interactive 3D T-Shirt • drag to rotate • scroll/pinch to zoom</p></div><span class="live-pill" id="modelStatus">STARTING 3D</span></div><div class="canvas-wrap" id="threeWrap"><div class="three-loading" id="threeLoading">Preparing 3D garment viewer…</div><div class="ground-note">T-SHIRT 3D MODEL • LIVE MATERIAL PREVIEW</div></div><div class="viewer-controls"><div class="view-buttons"><button data-view="front">FRONT</button><button data-view="back">BACK</button><button data-view="left">LEFT</button><button data-view="right">RIGHT</button><button data-view="reset">RESET</button></div></div><div class="viewer-help">The studio remains usable even if your browser cannot load the 3D model.</div></section>'+ 
'<div class="right-col"><div class="editor-card"><h2>2D ARTWORK EDITOR</h2><p class="editor-sub">Upload multiple logos/artwork or add text. Drag, resize and rotate using the object handles.</p><div class="placement-tabs" id="sideTabs"><button data-side="front" class="active">FRONT</button><button data-side="back">BACK</button><button data-side="leftSleeve">LEFT SLEEVE</button><button data-side="rightSleeve">RIGHT SLEEVE</button></div><div class="fabric-stage"><canvas id="designCanvas" width="520" height="360"></canvas><div id="fabricFallback" style="display:none;padding:24px;text-align:center">Artwork editor library could not load. Please check your internet/CDN connection.</div></div><label class="upload-label">UPLOAD LOGO / ARTWORK (PNG, JPG, SVG)<input id="uploadInput" type="file" accept=".png,.jpg,.jpeg,.svg,image/png,image/jpeg,image/svg+xml"></label><div class="text-grid"><input id="textInput" value="BLACK PINE" placeholder="Company, team, employee or slogan"><select id="fontSelect"><option>Arial</option><option>Helvetica</option><option>Georgia</option><option>Courier New</option><option>Impact</option></select><input id="textColor" type="color" value="#161918"><button id="addText">ADD TEXT</button></div><div class="tool-row"><button id="boldBtn">BOLD</button><button id="deleteBtn">DELETE</button><button id="clearBtn">CLEAR AREA</button></div></div>'+ 
'<div class="order-card" id="order"><h2>ORDER & DESIGN DATA</h2><div class="order-grid"><input id="qty" value="50" type="number" min="1" placeholder="Quantity"><input id="designName" placeholder="Design name (optional)"><textarea id="notes" placeholder="Production notes, fabric, GSM or special instructions"></textarea></div><div class="section-title" style="margin-top:10px">SELECT SIZES</div><div class="sizes">'+['XS','S','M','L','XL','2XL','3XL'].map(function(s){return '<button class="size-chip '+((s==='M'||s==='L')?'active':'')+'" data-size="'+s+'">'+s+'</button>';}).join('')+'</div><div class="studio-actions"><button id="saveBtn">SAVE DESIGN</button><button class="alt" id="loadBtn">LOAD</button><button class="alt" id="exportBtn">EXPORT JSON</button></div><div class="status" id="status"></div></div></div></div></div>';

function status(t){var e=document.getElementById('status');if(e)e.textContent=t;}
function syncColorUI(){document.getElementById('hexInput').value=colors[activeSection];document.getElementById('colorInput').value=colors[activeSection];}
function updateMaterialColors(){if(!garment)return;garment.traverse(function(o){if(!o.isMesh)return;var name=(o.name||'').toLowerCase();Object.keys(meshMap).forEach(function(sec){if(meshMap[sec].some(function(n){return name.indexOf(n)!==-1;})&&o.material&&o.material.color){o.material.color.set(colors[sec]);o.material.needsUpdate=true;}});});}
function initThree(){
 var wrap=document.getElementById('threeWrap'), loading=document.getElementById('threeLoading'), pill=document.getElementById('modelStatus');
 if(!window.THREE || !THREE.OrbitControls || !THREE.GLTFLoader){loading.textContent='3D viewer library could not load. The customization studio is still available.';pill.textContent='3D OFFLINE';return;}
 try{
  var w=Math.max(320,wrap.clientWidth),h=Math.max(460,wrap.clientHeight||560);
  scene=new THREE.Scene();scene.background=new THREE.Color(0xe9e7e1);
  camera=new THREE.PerspectiveCamera(35,w/h,.1,100);camera.position.set(0,.15,6);
  renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setSize(w,h);renderer.shadowMap.enabled=true;wrap.insertBefore(renderer.domElement,wrap.firstChild);
  controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=3.5;controls.maxDistance=8;controls.target.set(0,0,0);
  scene.add(new THREE.HemisphereLight(0xffffff,0x5d5d5d,2));var key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(3,5,4);key.castShadow=true;scene.add(key);var fill=new THREE.DirectionalLight(0xffffff,.8);fill.position.set(-4,2,2);scene.add(fill);
  var floor=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.ShadowMaterial({color:0x000000,opacity:.22}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.85;floor.receiveShadow=true;scene.add(floor);
  var loader=new THREE.GLTFLoader();loader.load('assets/models/tshirt.glb',function(g){garment=g.scene;garment.scale.setScalar(1.18);garment.traverse(function(o){if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material=o.material.clone();o.material.roughness=.78;o.material.metalness=.02;}}});scene.add(garment);updateMaterialColors();loading.style.display='none';pill.textContent='LIVE 3D';},undefined,function(){loading.textContent='3D model file could not load. Check assets/models/tshirt.glb after publishing.';pill.textContent='MODEL CHECK';});
  (function animate(){requestAnimationFrame(animate);if(controls)controls.update();renderer.render(scene,camera);})();
  window.addEventListener('resize',function(){if(!renderer)return;var ww=Math.max(320,wrap.clientWidth),hh=Math.max(460,wrap.clientHeight||560);camera.aspect=ww/hh;camera.updateProjectionMatrix();renderer.setSize(ww,hh);});
 }catch(err){console.error(err);loading.textContent='3D viewer could not start, but the rest of the studio is working.';pill.textContent='3D CHECK';}
}
function initFabric(){if(!window.fabric){document.getElementById('fabricFallback').style.display='block';return;}fabricCanvas=new fabric.Canvas('designCanvas',{preserveObjectStacking:true,backgroundColor:'rgba(255,255,255,0)'});var sync=function(){editorDesigns[activeSide]=fabricCanvas.toJSON(['placement','assetType']);};['object:added','object:modified','object:removed','text:changed'].forEach(function(e){fabricCanvas.on(e,sync);});}
function loadSide(side){if(fabricCanvas){var data=editorDesigns[side];fabricCanvas.clear();if(data)fabricCanvas.loadFromJSON(data,function(){fabricCanvas.renderAll();});}activeSide=side;document.querySelectorAll('#sideTabs button').forEach(function(b){b.classList.toggle('active',b.dataset.side===side);});}
function setView(v){if(!camera||!controls)return;if(v==='front')camera.position.set(0,0,6);if(v==='back')camera.position.set(0,0,-6);if(v==='left')camera.position.set(-6,0,0);if(v==='right')camera.position.set(6,0,0);if(v==='reset')camera.position.set(0,.15,6);controls.target.set(0,0,0);controls.update();}
function save(){var data={version:3,garmentType:'tshirt',colors:colors,designSurfaces:editorDesigns,quantity:document.getElementById('qty').value,sizes:Array.prototype.map.call(document.querySelectorAll('.size-chip.active'),function(x){return x.dataset.size;}),designName:document.getElementById('designName').value,notes:document.getElementById('notes').value,updatedAt:new Date().toISOString()};localStorage.setItem('blackPineDesign',JSON.stringify(data));status('Design saved locally in this browser.');}
function load(){var raw=localStorage.getItem('blackPineDesign');if(!raw){status('No saved design found in this browser.');return;}try{var d=JSON.parse(raw);colors=d.colors||colors;editorDesigns=d.designSurfaces||editorDesigns;document.getElementById('qty').value=d.quantity||50;document.getElementById('designName').value=d.designName||'';document.getElementById('notes').value=d.notes||'';document.querySelectorAll('.size-chip').forEach(function(b){b.classList.toggle('active',(d.sizes||[]).indexOf(b.dataset.size)!==-1);});loadSide(activeSide);updateMaterialColors();syncColorUI();status('Saved design restored.');}catch(e){status('Saved design could not be read.');}}
function exportData(){var data={garmentType:'tshirt',colors:colors,designSurfaces:editorDesigns,quantity:document.getElementById('qty').value};var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='black-pine-design.json';a.click();URL.revokeObjectURL(a.href);}

document.getElementById('sectionButtons').addEventListener('click',function(e){var s=e.target.dataset.section;if(!s)return;activeSection=s;document.querySelectorAll('#sectionButtons button').forEach(function(b){b.classList.toggle('active',b.dataset.section===s);});syncColorUI();});
document.getElementById('swatches').addEventListener('click',function(e){var c=e.target.dataset.color;if(!c)return;colors[activeSection]=c;syncColorUI();updateMaterialColors();});
document.getElementById('hexInput').addEventListener('input',function(e){var v=e.target.value;if(/^#[0-9a-fA-F]{6}$/.test(v)){colors[activeSection]=v;document.getElementById('colorInput').value=v;updateMaterialColors();}});
document.getElementById('colorInput').addEventListener('input',function(e){colors[activeSection]=e.target.value;syncColorUI();updateMaterialColors();});
document.querySelectorAll('#sideTabs button').forEach(function(b){b.onclick=function(){loadSide(b.dataset.side);};});
document.getElementById('uploadInput').onchange=function(e){if(!fabricCanvas){status('Artwork editor is unavailable because Fabric.js did not load.');return;}var f=e.target.files&&e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){fabric.Image.fromURL(r.result,function(img){img.scaleToWidth(Math.min(200,img.width));img.set({left:160,top:90,assetType:'artwork',placement:activeSide});fabricCanvas.add(img);fabricCanvas.setActiveObject(img);fabricCanvas.renderAll();});};r.readAsDataURL(f);e.target.value='';};
document.getElementById('addText').onclick=function(){if(!fabricCanvas){status('Artwork editor is unavailable because Fabric.js did not load.');return;}var o=new fabric.IText(document.getElementById('textInput').value||'Your Text',{left:150,top:140,fill:document.getElementById('textColor').value,fontFamily:document.getElementById('fontSelect').value,fontSize:42,fontWeight:'bold',assetType:'text',placement:activeSide});fabricCanvas.add(o);fabricCanvas.setActiveObject(o);fabricCanvas.renderAll();};
document.getElementById('boldBtn').onclick=function(){if(!fabricCanvas)return;var o=fabricCanvas.getActiveObject();if(o){o.set('fontWeight',o.fontWeight==='bold'?'normal':'bold');fabricCanvas.renderAll();}};
document.getElementById('deleteBtn').onclick=function(){if(!fabricCanvas)return;var o=fabricCanvas.getActiveObject();if(o)fabricCanvas.remove(o);};
document.getElementById('clearBtn').onclick=function(){if(fabricCanvas){fabricCanvas.clear();editorDesigns[activeSide]=null;}};
document.querySelectorAll('.view-buttons button').forEach(function(b){b.onclick=function(){setView(b.dataset.view);};});
document.querySelectorAll('.product-item.locked').forEach(function(b){b.onclick=function(){status(b.dataset.coming+' is ready in the shared customization workflow and will activate when its GLB model is added.');};});
document.querySelectorAll('.size-chip').forEach(function(b){b.onclick=function(){b.classList.toggle('active');};});
document.getElementById('saveBtn').onclick=save;document.getElementById('loadBtn').onclick=load;document.getElementById('exportBtn').onclick=exportData;
initFabric();initThree();syncColorUI();
})();
